//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Order
{
    public int OrderID { get; set; }
    public string CustomerName { get; set; }
    public string Dish { get; set; }
    public string Size { get; set; }
    public Nullable<bool> Chili { get; set; }
    public Nullable<bool> Pepper { get; set; }
    public Nullable<bool> MoreSalt { get; set; }
}
